name: scn_db_tools
channels:
  - conda-forge

dependencies:
  - python >=3.6
  - click
  - geopandas
  - openpyxl
  - pandas
  - pyproj
  - python-dateutil
  - requests
  - shapely
  - xcube_geodb >= 1.0.9
